# -*- mode: python ; coding: utf-8 -*-
import os, importlib.util

_langdetect_spec = importlib.util.find_spec('langdetect')
_langdetect_dir  = os.path.dirname(_langdetect_spec.origin) if _langdetect_spec else ''
_langdetect_profiles = os.path.join(_langdetect_dir, 'profiles')

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('assets/logo-home.png', 'assets'),
        ('assets/Foto_profilo.jpg', 'assets'),
        (_langdetect_profiles, 'langdetect/profiles'),
    ],
    hiddenimports=[
        'docs.targhetta',
        'docs.panel',
        'docs.jobs',
        'docs.params',
        'docs.names',
        'docs.utils',
        'docs.help_data',
        'docs.uf_tools',
        'docs.backup',
        'docs.drive',
        'docs.points',
        'docs.ga500_params',
        'docs.logdata',
        'docs.pdf_header',
        'docs.ipnet',
        'docs.ifpanel',
        'docs.flowchart',
        'docs.posvar',
        'gui.ifpanel_view',
        'gui.posvar_view',
        'gui.flowchart_view',
        'gui.help_view',
        'gui.uf_tools_view',
        'gui.uframe_view',
        'gui.tool_panel',
        'gui.login_window',
        'gui.top_bar',
        'openpyxl',
        'openpyxl.styles',
        'openpyxl.utils',
        'openpyxl.styles.fills',
        'openpyxl.styles.fonts',
        'openpyxl.styles.alignment',
        'reportlab',
        'reportlab.platypus',
        'reportlab.lib.pagesizes',
        'reportlab.lib.styles',
        'reportlab.lib.units',
        'reportlab.lib.colors',
        'reportlab.lib.enums',
        'reportlab.platypus.tableofcontents',
        'reportlab.pdfbase',
        'reportlab.pdfbase.pdfmetrics',
        'reportlab.pdfbase.cidfonts',
        'reportlab.pdfbase.ttfonts',
        'PIL',
        'PIL.Image',
        'PIL.BmpImagePlugin',
        'psutil',
        'translations',
        'logger',
        'secure_paths',
        'auth',
        'config',
        'tooltips',
        'langdetect',
        'langdetect.detector',
        'langdetect.detector_factory',
        'langdetect.language',
        'langdetect.lang_detect_exception',
        'deep_translator',
        'deep_translator.google',
        'deep_translator.base',
        'deep_translator.exceptions',
        'beautifulsoup4',
        'bs4',
        'soupsieve',
        'pypdf',
        'pypdf.generic',
        'pypdf._reader',
        'urllib',
        'urllib.request',
        'urllib.parse',
        'urllib.error',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='YaskawaTools',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,          # UPX non supportato su macOS arm64
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    # Security (v1.1.6): suppress the windowed traceback dialog so an unhandled
    # exception never exposes internal stack/paths to the end user.
    disable_windowed_traceback=True,
    argv_emulation=False,
    target_arch=None,   # None = architettura nativa del runner (arm64 su macos-latest)
    codesign_identity=None,
    entitlements_file=None,
)

app = BUNDLE(
    exe,
    name='YaskawaTools.app',
    icon=None,          # Aggiungere un .icns qui se disponibile
    bundle_identifier='com.othack1a.yaskawatools',
    info_plist={
        'NSHighResolutionCapable': True,
        'LSMinimumSystemVersion': '12.0',
        'CFBundleShortVersionString': '1.1.6',
        'CFBundleVersion': '1',
        'NSHumanReadableCopyright': 'Copyright © 2025 0THack1A',
    },
)
