"""Descriptive tooltips for every interactive widget, in 7 languages.

The text describes WHAT the action does (not just the label that's already
visible).  Keys correspond to the attribute name of the QAction / QPushButton
on the owning widget (e.g. ``action_ipnet``, ``btn_close``).  Fallback chain:
selected language → IT → empty string.
"""

# fmt: off
TIPS = {
    # ── Top-level menus ──────────────────────────────────────────────────────
    "menu_file": {
        "IT": "Operazioni su file: rete, log dati, compilazione, uscita",
        "EN": "File operations: network, log data, compile, exit",
        "FR": "Opérations sur fichiers : réseau, journal, compilation, sortie",
        "DE": "Dateioperationen: Netzwerk, Log, Kompilieren, Beenden",
        "ES": "Operaciones de archivo: red, registro, compilar, salir",
        "UA": "Файлові операції: мережа, журнал, компіляція, вихід",
        "JA": "ファイル操作：ネットワーク・ログ・コンパイル・終了",
    },
    "menu_genera": {
        "IT": "Genera template Excel, configurazioni e file DAT",
        "EN": "Generate Excel templates, configurations and DAT files",
        "FR": "Génère des modèles Excel, configurations et fichiers DAT",
        "DE": "Erzeugt Excel-Vorlagen, Konfigurationen und DAT-Dateien",
        "ES": "Genera plantillas Excel, configuraciones y archivos DAT",
        "UA": "Створює шаблони Excel, конфігурації та DAT-файли",
        "JA": "Excelテンプレート、設定、DATファイルを生成します",
    },
    "menu_documentation": {
        "IT": "Genera documentazione PDF di ogni sezione del robot",
        "EN": "Generate PDF documentation for every robot section",
        "FR": "Génère la documentation PDF de chaque section du robot",
        "DE": "Erzeugt PDF-Dokumentation für jede Roboter-Sektion",
        "ES": "Genera documentación PDF de cada sección del robot",
        "UA": "Створює PDF-документацію для кожної секції робота",
        "JA": "ロボットの各セクションのPDFドキュメントを生成します",
    },
    "menu_backup": {
        "IT": "Esporta dati di backup (variabili, punti)",
        "EN": "Export backup data (variables, points)",
        "FR": "Exporte les données de sauvegarde (variables, points)",
        "DE": "Sicherungsdaten exportieren (Variablen, Punkte)",
        "ES": "Exporta datos de respaldo (variables, puntos)",
        "UA": "Експортує дані резервної копії (змінні, точки)",
        "JA": "バックアップデータ（変数・ポイント）をエクスポートします",
    },
    "menu_drive": {
        "IT": "Lettura e documentazione file MotionDrive",
        "EN": "MotionDrive file reading and documentation",
        "FR": "Lecture et documentation des fichiers MotionDrive",
        "DE": "MotionDrive-Dateien lesen und dokumentieren",
        "ES": "Lectura y documentación de archivos MotionDrive",
        "UA": "Зчитування та документація файлів MotionDrive",
        "JA": "MotionDriveファイルの読み込みとドキュメント生成",
    },
    "menu_help": {
        "IT": "Guida, parametri di riferimento, log e informazioni",
        "EN": "Guide, reference parameters, log and info",
        "FR": "Guide, paramètres de référence, journal et informations",
        "DE": "Anleitung, Referenzparameter, Protokoll und Info",
        "ES": "Guía, parámetros de referencia, registro e información",
        "UA": "Довідка, довідкові параметри, журнал та інформація",
        "JA": "ガイド、リファレンスパラメータ、ログ、情報",
    },

    # ── File menu actions ────────────────────────────────────────────────────
    "action_ipnet": {
        "IT": "Legge la configurazione di rete dal backup del robot",
        "EN": "Reads the network configuration from the robot backup",
        "FR": "Lit la configuration réseau depuis la sauvegarde du robot",
        "DE": "Liest die Netzwerkkonfiguration aus der Roboter-Sicherung",
        "ES": "Lee la configuración de red desde la copia del robot",
        "UA": "Зчитує мережеву конфігурацію з резервної копії робота",
        "JA": "ロボットのバックアップからネットワーク設定を読み取ります",
    },
    "action_logdata": {
        "IT": "Importa e visualizza il file LOGDATA.DAT del robot",
        "EN": "Imports and displays the robot's LOGDATA.DAT file",
        "FR": "Importe et affiche le fichier LOGDATA.DAT du robot",
        "DE": "Importiert und zeigt die LOGDATA.DAT-Datei des Roboters",
        "ES": "Importa y muestra el archivo LOGDATA.DAT del robot",
        "UA": "Імпортує та відображає файл LOGDATA.DAT робота",
        "JA": "ロボットのLOGDATA.DATファイルをインポート・表示",
    },
    "action_compila": {
        "IT": "Scrive valori nelle variabili del robot (VAR.DAT)",
        "EN": "Writes values to robot variables (VAR.DAT)",
        "FR": "Écrit des valeurs dans les variables du robot (VAR.DAT)",
        "DE": "Schreibt Werte in die Robotervariablen (VAR.DAT)",
        "ES": "Escribe valores en las variables del robot (VAR.DAT)",
        "UA": "Записує значення у змінні робота (VAR.DAT)",
        "JA": "ロボット変数（VAR.DAT）に値を書き込みます",
    },
    "action_exit": {
        "IT": "Chiude l'applicazione",
        "EN": "Closes the application",
        "FR": "Ferme l'application",
        "DE": "Schließt die Anwendung",
        "ES": "Cierra la aplicación",
        "UA": "Закриває програму",
        "JA": "アプリケーションを終了します",
    },

    # ── Genera menu actions ──────────────────────────────────────────────────
    "action_template": {
        "IT": "Crea un template Excel per i nomi di variabili e I/O",
        "EN": "Creates an Excel template for variable and I/O names",
        "FR": "Crée un modèle Excel pour les noms de variables et E/S",
        "DE": "Erstellt eine Excel-Vorlage für Variablen- und E/A-Namen",
        "ES": "Crea una plantilla Excel para nombres de variables y E/S",
        "UA": "Створює шаблон Excel для імен змінних і входів/виходів",
        "JA": "変数とI/O名のExcelテンプレートを作成します",
    },
    "action_nomi": {
        "IT": "Importa nomi da Excel e genera i file DAT per il robot",
        "EN": "Imports names from Excel and generates DAT files for the robot",
        "FR": "Importe des noms depuis Excel et génère les fichiers DAT",
        "DE": "Importiert Namen aus Excel und erzeugt DAT-Dateien",
        "ES": "Importa nombres desde Excel y genera archivos DAT",
        "UA": "Імпортує імена з Excel і генерує DAT-файли",
        "JA": "Excelから名前をインポートしてDATファイルを生成",
    },
    "action_tool": {
        "IT": "Configura ed esporta i dati dei tool TCP (fino a 64)",
        "EN": "Configures and exports TCP tool data (up to 64 tools)",
        "FR": "Configure et exporte les données des outils TCP (jusqu'à 64)",
        "DE": "Konfiguriert und exportiert TCP-Werkzeugdaten (bis 64)",
        "ES": "Configura y exporta datos de herramientas TCP (hasta 64)",
        "UA": "Налаштовує та експортує дані TCP-інструментів (до 64)",
        "JA": "TCPツールデータの設定・エクスポート（最大64）",
    },
    "action_uf": {
        "IT": "Visualizza e modifica i 63 User Frame (UFRAME.CND)",
        "EN": "Views and edits the 63 User Frames (UFRAME.CND)",
        "FR": "Affiche et modifie les 63 User Frames (UFRAME.CND)",
        "DE": "Zeigt und bearbeitet die 63 User Frames (UFRAME.CND)",
        "ES": "Visualiza y edita los 63 User Frames (UFRAME.CND)",
        "UA": "Переглядає та редагує 63 User Frame (UFRAME.CND)",
        "JA": "63のUser Frame（UFRAME.CND）を表示・編集",
    },
    "action_ifpanel": {
        "IT": "Legge e modifica IFPANEL.DAT (pannello operatore)",
        "EN": "Reads and edits IFPANEL.DAT (operator panel)",
        "FR": "Lit et modifie IFPANEL.DAT (panneau opérateur)",
        "DE": "Liest und bearbeitet IFPANEL.DAT (Bedienpanel)",
        "ES": "Lee y edita IFPANEL.DAT (panel de operador)",
        "UA": "Зчитує та редагує IFPANEL.DAT (операторська панель)",
        "JA": "IFPANEL.DAT（オペレーターパネル）の読み書き",
    },

    # ── Documentazione menu actions ──────────────────────────────────────────
    "action_flowchart": {
        "IT": "Visualizza i diagrammi di flusso dei JBI (export PDF/draw.io)",
        "EN": "Displays JBI flowcharts (export PDF/draw.io)",
        "FR": "Affiche les organigrammes JBI (export PDF/draw.io)",
        "DE": "Zeigt JBI-Flussdiagramme (Export PDF/draw.io)",
        "ES": "Muestra los diagramas de flujo JBI (export PDF/draw.io)",
        "UA": "Відображає блок-схеми JBI (експорт PDF/draw.io)",
        "JA": "JBIのフローチャートを表示（PDF/draw.ioエクスポート）",
    },
    "action_targhetta": {
        "IT": "Genera PDF con le informazioni di sistema da SYSTEM.SYS",
        "EN": "Generates PDF with system info from SYSTEM.SYS",
        "FR": "Génère un PDF avec les informations système (SYSTEM.SYS)",
        "DE": "Erzeugt PDF mit Systeminformationen aus SYSTEM.SYS",
        "ES": "Genera PDF con información del sistema desde SYSTEM.SYS",
        "UA": "Створює PDF із системною інформацією з SYSTEM.SYS",
        "JA": "SYSTEM.SYSのシステム情報からPDFを生成します",
    },
    "action_panel": {
        "IT": "Genera PDF del pannello con parametri e configurazione",
        "EN": "Generates PDF of the panel with parameters and configuration",
        "FR": "Génère un PDF du panneau avec paramètres et configuration",
        "DE": "Erzeugt PDF des Panels mit Parametern und Konfiguration",
        "ES": "Genera PDF del panel con parámetros y configuración",
        "UA": "Створює PDF панелі з параметрами та конфігурацією",
        "JA": "パラメータと設定を含むパネルのPDFを生成",
    },
    "action_jobs": {
        "IT": "Analizza i JBI e genera PDF con sommario e albero di richiamo",
        "EN": "Analyzes JBI files and generates PDF with summary and call tree",
        "FR": "Analyse les JBI et génère un PDF avec sommaire et arbre d'appels",
        "DE": "Analysiert JBI-Dateien und erzeugt PDF mit Aufrufbaum",
        "ES": "Analiza JBI y genera PDF con resumen y árbol de llamadas",
        "UA": "Аналізує JBI і створює PDF з підсумком і деревом викликів",
        "JA": "JBIを解析し、サマリーとコールツリーのPDFを生成",
    },
    "action_params": {
        "IT": "Genera PDF dei parametri non-zero da ALL.PRM",
        "EN": "Generates PDF of non-zero parameters from ALL.PRM",
        "FR": "Génère un PDF des paramètres non-zéro depuis ALL.PRM",
        "DE": "Erzeugt PDF der Nicht-Null-Parameter aus ALL.PRM",
        "ES": "Genera PDF de parámetros no-cero desde ALL.PRM",
        "UA": "Створює PDF ненульових параметрів з ALL.PRM",
        "JA": "ALL.PRMの非ゼロパラメータのPDFを生成します",
    },
    "action_uf_tools": {
        "IT": "Genera PDF con tool TCP e User Frame configurati",
        "EN": "Generates PDF with configured TCP tools and User Frames",
        "FR": "Génère un PDF avec les outils TCP et User Frames configurés",
        "DE": "Erzeugt PDF mit konfigurierten TCP-Werkzeugen und User Frames",
        "ES": "Genera PDF con herramientas TCP y User Frames configurados",
        "UA": "Створює PDF з налаштованими TCP-інструментами та User Frame",
        "JA": "設定済みTCPツールとUser FrameのPDFを生成",
    },
    "action_usrgrp": {
        "IT": "Visualizza e modifica gli User Group (GPIN/GPOT)",
        "EN": "Views and edits User Groups (GPIN/GPOT)",
        "FR": "Affiche et modifie les User Groups (GPIN/GPOT)",
        "DE": "Zeigt und bearbeitet User Groups (GPIN/GPOT)",
        "ES": "Visualiza y edita los User Groups (GPIN/GPOT)",
        "UA": "Переглядає та редагує User Group (GPIN/GPOT)",
        "JA": "User Group（GPIN/GPOT）を表示・編集",
    },
    "action_cubeintf": {
        "IT": "Analizza CUBEINTF.CND e genera il PDF dei cubi di interferenza attivi",
        "EN": "Parses CUBEINTF.CND and generates the PDF of active interference cubes",
        "FR": "Analyse CUBEINTF.CND et génère le PDF des cubes d'interférence actifs",
        "DE": "Analysiert CUBEINTF.CND und erzeugt das PDF der aktiven Interferenzwürfel",
        "ES": "Analiza CUBEINTF.CND y genera el PDF de los cubos de interferencia activos",
        "UA": "Аналізує CUBEINTF.CND і створює PDF активних кубів інтерференції",
        "JA": "CUBEINTF.CND を解析し、アクティブな干渉キューブのPDFを生成します",
    },
    "action_formcut": {
        "IT": "Analizza FORMCUT.CND e genera il PDF delle sagome di taglio (Form Cut)",
        "EN": "Parses FORMCUT.CND and generates the Form Cut shapes PDF",
        "FR": "Analyse FORMCUT.CND et génère le PDF des formes de découpe (Form Cut)",
        "DE": "Analysiert FORMCUT.CND und erzeugt das PDF der Form-Cut-Formen",
        "ES": "Analiza FORMCUT.CND y genera el PDF de las formas de corte (Form Cut)",
        "UA": "Аналізує FORMCUT.CND і створює PDF форм різання (Form Cut)",
        "JA": "FORMCUT.CND を解析し、フォームカット形状のPDFを生成します",
    },
    "action_completa": {
        "IT": "Genera un PDF completo con tutte le sezioni e gli allegati",
        "EN": "Generates a complete PDF with all sections and attachments",
        "FR": "Génère un PDF complet avec toutes les sections et pièces jointes",
        "DE": "Erzeugt ein vollständiges PDF mit allen Sektionen und Anhängen",
        "ES": "Genera un PDF completo con todas las secciones y anexos",
        "UA": "Створює повний PDF з усіма секціями та додатками",
        "JA": "全セクションと添付ファイルを含む完全なPDFを生成",
    },

    # ── Backup menu actions ──────────────────────────────────────────────────
    "action_backup_var": {
        "IT": "Esporta le variabili del robot in Excel",
        "EN": "Exports robot variables to Excel",
        "FR": "Exporte les variables du robot vers Excel",
        "DE": "Exportiert Robotervariablen nach Excel",
        "ES": "Exporta las variables del robot a Excel",
        "UA": "Експортує змінні робота в Excel",
        "JA": "ロボット変数をExcelにエクスポートします",
    },
    "action_backup_punti": {
        "IT": "Esporta in PDF le posizioni dei programmi JBI",
        "EN": "Exports JBI program positions to PDF",
        "FR": "Exporte en PDF les positions des programmes JBI",
        "DE": "Exportiert die JBI-Programmpositionen als PDF",
        "ES": "Exporta a PDF las posiciones de los programas JBI",
        "UA": "Експортує в PDF позиції програм JBI",
        "JA": "JBIプログラムの位置をPDFにエクスポートします",
    },

    # ── Drive menu actions ───────────────────────────────────────────────────
    "action_motion_drive": {
        "IT": "Apre un file .YDWIProj/.YDWGProj e genera PDF/Excel",
        "EN": "Opens a .YDWIProj/.YDWGProj file and generates PDF/Excel",
        "FR": "Ouvre un fichier .YDWIProj/.YDWGProj et génère PDF/Excel",
        "DE": "Öffnet eine .YDWIProj/.YDWGProj-Datei und erzeugt PDF/Excel",
        "ES": "Abre un archivo .YDWIProj/.YDWGProj y genera PDF/Excel",
        "UA": "Відкриває файл .YDWIProj/.YDWGProj і створює PDF/Excel",
        "JA": ".YDWIProj/.YDWGProjファイルを開いてPDF/Excelを生成",
    },

    # ── Help menu actions ────────────────────────────────────────────────────
    "action_log": {
        "IT": "Mostra/nasconde il pannello dei log",
        "EN": "Shows/hides the log panel",
        "FR": "Affiche/masque le panneau de journal",
        "DE": "Zeigt/verbirgt das Log-Panel",
        "ES": "Muestra/oculta el panel de registro",
        "UA": "Показує/приховує панель журналу",
        "JA": "ログパネルの表示/非表示を切り替えます",
    },
    "action_ga500_params": {
        "IT": "Elenco parametri YASKAWA GA500 con ricerca",
        "EN": "YASKAWA GA500 parameter list with search",
        "FR": "Liste des paramètres YASKAWA GA500 avec recherche",
        "DE": "YASKAWA GA500-Parameterliste mit Suche",
        "ES": "Lista de parámetros YASKAWA GA500 con búsqueda",
        "UA": "Список параметрів YASKAWA GA500 з пошуком",
        "JA": "検索付きYASKAWA GA500パラメータリスト",
    },
    "action_help_params": {
        "IT": "Elenco dei parametri YRC1000 con descrizioni",
        "EN": "YRC1000 parameter list with descriptions",
        "FR": "Liste des paramètres YRC1000 avec descriptions",
        "DE": "YRC1000-Parameterliste mit Beschreibungen",
        "ES": "Lista de parámetros YRC1000 con descripciones",
        "UA": "Список параметрів YRC1000 з описами",
        "JA": "説明付きYRC1000パラメータリスト",
    },
    "action_help_known": {
        "IT": "Parametri YRC1000 con valori consigliati noti",
        "EN": "YRC1000 parameters with known recommended values",
        "FR": "Paramètres YRC1000 avec valeurs recommandées connues",
        "DE": "YRC1000-Parameter mit bekannten empfohlenen Werten",
        "ES": "Parámetros YRC1000 con valores recomendados conocidos",
        "UA": "Параметри YRC1000 з відомими рекомендованими значеннями",
        "JA": "推奨値付きYRC1000パラメータ",
    },
    "action_about": {
        "IT": "Mostra versione, info ambiente e creator",
        "EN": "Shows version, environment info and creator",
        "FR": "Affiche la version, les infos d'environnement et le créateur",
        "DE": "Zeigt Version, Umgebungsinfo und Ersteller",
        "ES": "Muestra versión, info de entorno y creador",
        "UA": "Показує версію, інформацію про середовище та творця",
        "JA": "バージョン、環境情報、クリエイターを表示",
    },
    "action_aiuto": {
        "IT": "Apre la guida rapida del programma",
        "EN": "Opens the quick start guide",
        "FR": "Ouvre le guide rapide du programme",
        "DE": "Öffnet die Schnellanleitung",
        "ES": "Abre la guía rápida del programa",
        "UA": "Відкриває коротку довідку програми",
        "JA": "プログラムのクイックガイドを開きます",
    },

    # ── Common buttons (matched by button text or attribute) ─────────────────
    "btn_login": {
        "IT": "Verifica la password ed entra nel programma",
        "EN": "Verifies the password and enters the program",
        "FR": "Vérifie le mot de passe et entre dans le programme",
        "DE": "Prüft das Passwort und betritt das Programm",
        "ES": "Verifica la contraseña y entra en el programa",
        "UA": "Перевіряє пароль і входить у програму",
        "JA": "パスワードを確認してプログラムに入ります",
    },
    "btn_exit": {
        "IT": "Chiude l'applicazione",
        "EN": "Closes the application",
        "FR": "Ferme l'application",
        "DE": "Schließt die Anwendung",
        "ES": "Cierra la aplicación",
        "UA": "Закриває програму",
        "JA": "アプリケーションを終了します",
    },
    "txt_password": {
        "IT": "Inserisci la password (case-sensitive). Max 3 tentativi.",
        "EN": "Enter password (case-sensitive). Max 3 attempts.",
        "FR": "Saisissez le mot de passe (sensible à la casse). 3 essais max.",
        "DE": "Passwort eingeben (Groß-/Kleinschreibung). Max. 3 Versuche.",
        "ES": "Introduce la contraseña (mayúsculas y minúsculas). Máx. 3 intentos.",
        "UA": "Введіть пароль (з урахуванням регістру). Макс. 3 спроби.",
        "JA": "パスワードを入力（大文字小文字区別）。最大3回試行。",
    },
    "preview_close": {
        "IT": "Chiude l'anteprima e torna alla pagina principale",
        "EN": "Closes the preview and returns to the main page",
        "FR": "Ferme l'aperçu et retourne à la page principale",
        "DE": "Schließt die Vorschau und kehrt zur Hauptseite zurück",
        "ES": "Cierra la vista previa y vuelve a la página principal",
        "UA": "Закриває попередній перегляд і повертає на головну",
        "JA": "プレビューを閉じてメインページに戻ります",
    },
    "btn_generate_pdf": {
        "IT": "Genera/aggiorna il PDF della sezione corrente",
        "EN": "Generates/refreshes the PDF of the current section",
        "FR": "Génère/actualise le PDF de la section actuelle",
        "DE": "Erzeugt/aktualisiert das PDF des aktuellen Bereichs",
        "ES": "Genera/actualiza el PDF de la sección actual",
        "UA": "Створює/оновлює PDF поточної секції",
        "JA": "現在のセクションのPDFを生成・更新します",
    },
    "btn_export_pdf": {
        "IT": "Salva il PDF su disco",
        "EN": "Saves the PDF to disk",
        "FR": "Enregistre le PDF sur disque",
        "DE": "Speichert das PDF auf der Festplatte",
        "ES": "Guarda el PDF en disco",
        "UA": "Зберігає PDF на диск",
        "JA": "PDFをディスクに保存します",
    },
    "btn_export_excel": {
        "IT": "Esporta i dati in formato Excel (.xlsx)",
        "EN": "Exports data to Excel (.xlsx) format",
        "FR": "Exporte les données au format Excel (.xlsx)",
        "DE": "Exportiert die Daten als Excel (.xlsx)",
        "ES": "Exporta los datos en formato Excel (.xlsx)",
        "UA": "Експортує дані у формат Excel (.xlsx)",
        "JA": "データをExcel（.xlsx）形式でエクスポート",
    },
    "btn_generate_excel": {
        "IT": "Genera il file Excel della sezione",
        "EN": "Generates the Excel file for the section",
        "FR": "Génère le fichier Excel de la section",
        "DE": "Erzeugt die Excel-Datei des Bereichs",
        "ES": "Genera el archivo Excel de la sección",
        "UA": "Створює Excel-файл секції",
        "JA": "セクションのExcelファイルを生成します",
    },
    "btn_modifica": {
        "IT": "Passa in modalità modifica",
        "EN": "Switches to edit mode",
        "FR": "Passe en mode édition",
        "DE": "Wechselt in den Bearbeitungsmodus",
        "ES": "Cambia al modo edición",
        "UA": "Перемикає в режим редагування",
        "JA": "編集モードに切り替えます",
    },
    "btn_back": {
        "IT": "Torna alla schermata precedente",
        "EN": "Returns to the previous screen",
        "FR": "Retourne à l'écran précédent",
        "DE": "Zurück zum vorherigen Bildschirm",
        "ES": "Vuelve a la pantalla anterior",
        "UA": "Повертається до попереднього екрана",
        "JA": "前の画面に戻ります",
    },
    "btn_export_groups": {
        "IT": "Salva gli User Group nei file DAT del robot",
        "EN": "Saves the User Groups into the robot's DAT files",
        "FR": "Enregistre les User Groups dans les fichiers DAT du robot",
        "DE": "Speichert die User Groups in die DAT-Dateien des Roboters",
        "ES": "Guarda los User Groups en los archivos DAT del robot",
        "UA": "Зберігає User Groups у DAT-файли робота",
        "JA": "User GroupsをロボットのDATファイルに保存します",
    },
    "zoom_in": {
        "IT": "Aumenta lo zoom",
        "EN": "Zoom in",
        "FR": "Zoom avant",
        "DE": "Vergrößern",
        "ES": "Acercar",
        "UA": "Збільшити масштаб",
        "JA": "ズームイン",
    },
    "zoom_out": {
        "IT": "Diminuisce lo zoom",
        "EN": "Zoom out",
        "FR": "Zoom arrière",
        "DE": "Verkleinern",
        "ES": "Alejar",
        "UA": "Зменшити масштаб",
        "JA": "ズームアウト",
    },
    "preview_open_file": {
        "IT": "Apre il PDF nel visualizzatore esterno",
        "EN": "Opens the PDF in the external viewer",
        "FR": "Ouvre le PDF dans le lecteur externe",
        "DE": "Öffnet das PDF im externen Viewer",
        "ES": "Abre el PDF en el visor externo",
        "UA": "Відкриває PDF у зовнішньому переглядачі",
        "JA": "PDFを外部ビューアで開きます",
    },
    "preview_open_folder": {
        "IT": "Apre la cartella che contiene il PDF",
        "EN": "Opens the folder containing the PDF",
        "FR": "Ouvre le dossier contenant le PDF",
        "DE": "Öffnet den Ordner mit dem PDF",
        "ES": "Abre la carpeta que contiene el PDF",
        "UA": "Відкриває папку з PDF",
        "JA": "PDFが入っているフォルダを開きます",
    },
    "work_folder_btn": {
        "IT": "Seleziona la cartella di backup del robot",
        "EN": "Selects the robot backup folder",
        "FR": "Sélectionne le dossier de sauvegarde du robot",
        "DE": "Wählt den Sicherungsordner des Roboters",
        "ES": "Selecciona la carpeta de copia del robot",
        "UA": "Вибирає папку резервної копії робота",
        "JA": "ロボットのバックアップフォルダを選択します",
    },
    "btn_genera": {
        "IT": "Genera il PDF della sezione corrente",
        "EN": "Generates the PDF of the current section",
        "FR": "Génère le PDF de la section actuelle",
        "DE": "Erzeugt das PDF des aktuellen Bereichs",
        "ES": "Genera el PDF de la sección actual",
        "UA": "Створює PDF поточної секції",
        "JA": "現在のセクションのPDFを生成します",
    },
    "flowchart_btn_export_pdf": {
        "IT": "Esporta il PDF dei diagrammi di flusso",
        "EN": "Exports the flowchart PDF",
        "FR": "Exporte le PDF des organigrammes",
        "DE": "Exportiert das Flussdiagramm-PDF",
        "ES": "Exporta el PDF de los diagramas de flujo",
        "UA": "Експортує PDF блок-схем",
        "JA": "フローチャートのPDFをエクスポート",
    },
    "flowchart_btn_export_drawio": {
        "IT": "Esporta i diagrammi nel formato draw.io",
        "EN": "Exports the diagrams in draw.io format",
        "FR": "Exporte les diagrammes au format draw.io",
        "DE": "Exportiert die Diagramme im draw.io-Format",
        "ES": "Exporta los diagramas en formato draw.io",
        "UA": "Експортує діаграми у форматі draw.io",
        "JA": "図をdraw.io形式でエクスポート",
    },
}
# fmt: on


def get(key: str, lang: str) -> str:
    """Return the tooltip text for *key* in *lang*, with IT/empty fallback."""
    entry = TIPS.get(key)
    if not entry:
        return ""
    return entry.get(lang) or entry.get("IT") or ""
