# Embedded YASKAWA YRC1000 parameter reference — multilingual.
# Codes and values are language-independent; only descriptions are translated.
# To add a parameter: append one entry to each _*_CODES/_VALUES list AND one
# description string (in the same position) to every _*_DESC_XX list.

# ═══════════════════════════════════════════════════════════════════════════════
# PARAMS_DATA  (source: YASKAWA.md)  — 2 columns: code, description
# ═══════════════════════════════════════════════════════════════════════════════

_PARAMS_CODES = [
    "S0C682",       "S1CxG000",     "S1CxG045",     "S1CxG046",
    "S1CxG047",     "S1CxG048",     "S1CxG056",     "S1CxG057",
    "S1CxG060",     "S1CxG061",     "S1CxG062",     "S1CxG202",
    "S1CxG203",     "S2C196",       "S2C201",       "S2C203",
    "S2C206",       "S2C211",       "S2C214",       "S2C231",
    "S2C234",       "S2C320",       "S2C333",       "S2C400",
    "S2C413",       "S2C431",       "S2C432",       "S2C433",
    "S2C434",       "S2C688",       "S2C1503",      "S3C008-011",
    "S4C032-047",   "S4C048-063",   "S4C1132-1147", "S4C1148-1163",
    "S4C1180",      "S4C1181",      "S4C1182",      "S4C1183",
    "S4C1184",      "S4C1185",      "S4C1186",      "S4C1187",
    "S4C1188",      "S4C1189-1192", "S4C1193",      "AxP000",
    "AxP003",
]

_PARAMS_DESC_IT = [
    "Limita la creazione del file di backup automatico a una sola volta al giorno (0: Disabilitato, 1: Abilitato).",
    "Limite superiore di velocità per l'operazione IN-GUARD-SAFE (unità: 0,01%).",
    "Velocità di collegamento per l'operazione di Jog al livello LOW.",
    "Velocità di collegamento per l'operazione di Jog al livello MEDIUM.",
    "Velocità di collegamento per l'operazione di Jog al livello HIGH.",
    "Velocità di collegamento per l'operazione di Jog al livello HIGH SPEED.",
    "Velocità di ritorno alla posizione WORK HOME rispetto alla velocità massima (unità: 0,01%).",
    "Velocità massima per le funzioni di ricerca (Search) (unità: 0,1 mm/s).",
    "Limitazione velocità manuale per il funzionamento passo-passo (unità: 0,01%).",
    "Limitazione velocità manuale per il funzionamento Bassa (unità: 0,01%).",
    "Limitazione velocità manuale per il funzionamento Mid (unità: 0,01%).",
    "Specifica (in bit) l'asse per l'output della posizione attuale (comando) nei registri.",
    "Specifica (in bit) l'asse per l'output della posizione attuale (feedback) nei registri.",
    "Definisce se le coordinate del robot sono ad angolo retto (0) o cilindriche (1).",
    "Controllo della postura durante l'operazione cartesiana di Jog.",
    "Permette (0) o blocca (1) la sola modifica dei passi nel programma.",
    "Inserimento istruzione MOVE: sotto la riga (0) o dopo il prossimo passo (1).",
    "Definisce il livello del linguaggio INFORM (0: Base, 1: Standard, 2: Esteso).",
    "Abilita (1) o disabilita (0) il mantenimento dei valori delle istruzioni nella riga messaggio.",
    "Imposta la modalità Passo/Procedura di test su FACILE (0) o TUTTO (1).",
    "Protezione in scrittura del numero utensile per il post-teach.",
    "Consente (0) o blocca (1) il post-teach del solo gruppo di assi spostato.",
    "Abilita (1) o disabilita (0) la funzione di commutazione del numero utensile (TOOL NO. SWITCHING).",
    "Parametro necessario per abilitare l'uso del comando SETUALM (Allarme utente).",
    "Attiva (1) o disabilita (0) il cestino per il ripristino dei JOB cancellati.",
    "Permette (0) o blocca (1) l'uso di 64 file utensile (TCP).",
    "Metodo calibrazione utensile: solo coordinate (0), solo posizione (1), coordinate e posizione (2).",
    "Attiva (0) o disattiva (1) il segnale acustico (bip) durante il teach delle posizioni.",
    "Abilita (1) o disabilita (0) la visualizzazione delle coordinate doppie con funzione SHIFT.",
    "Permette o blocca il passo all'indietro (BWD) senza gruppo asse o in job paralleli.",
    "Funzione di miglioramento dell'elaborazione della visualizzazione degli allarmi.",
    "Limiti software per il Robot 2 sui lati positivi e negativi degli assi X, Y e Z.",
    "Specifica se i dati dei gruppi di input (1-256) sono gestiti come binari o BCD.",
    "Specifica se i dati dei gruppi di output (1-256) sono gestiti come binari o BCD.",
    "Gestione dati (binario/BCD) per i gruppi di input da 257 a 512.",
    "Gestione dati (binario/BCD) per i gruppi di output da 257 a 512.",
    "Parametro relativo al File Utensile (Tool File) nella sicurezza funzionale (FSU).",
    "File di protezione dalle interferenze dell'utensile (FSU).",
    "Dati di calibrazione della posizione Home (FSU).",
    "Dati del limite del raggio d'azione degli assi (FSU).",
    "Dati di monitoraggio della velocità degli assi (FSU).",
    "Dati del limite del raggio d'azione del robot (FSU).",
    "Dati del limite di velocità (FSU).",
    "Dati di monitoraggio dell'angolo dell'utensile (FSU).",
    "Monitoraggio cambio utensile / Selezione numero utensile (FSU).",
    "Parametri di definizione funzionale, sistema, SERVO e servomotore (FSU).",
    "Parametro di corrispondenza robot (Robot match parameter) per l'istruzione SETTOOL.",
    "Specifica l'applicazione (es. 0 per la saldatura ad arco).",
    "Assegnazione file condizioni inizio saldatura per la sorgente di alimentazione 2.",
]

_PARAMS_DESC_EN = [
    "Limits automatic backup file creation to once per day (0: Disabled, 1: Enabled).",
    "Upper speed limit for the IN-GUARD-SAFE operation (unit: 0.01%).",
    "Link speed for Jog operation at LOW level.",
    "Link speed for Jog operation at MEDIUM level.",
    "Link speed for Jog operation at HIGH level.",
    "Link speed for Jog operation at HIGH SPEED level.",
    "Return speed to WORK HOME position relative to maximum speed (unit: 0.01%).",
    "Maximum speed for Search functions (unit: 0.1 mm/s).",
    "Manual speed limit for step-by-step operation (unit: 0.01%).",
    "Manual speed limit for Low speed operation (unit: 0.01%).",
    "Manual speed limit for Mid speed operation (unit: 0.01%).",
    "Specifies (in bits) the axis for current position (command) output in registers.",
    "Specifies (in bits) the axis for current position (feedback) output in registers.",
    "Defines whether robot coordinates are rectangular (0) or cylindrical (1).",
    "Posture control during Cartesian Jog operation.",
    "Allows (0) or prevents (1) modification of steps only in the program.",
    "MOVE instruction insertion: below the line (0) or after the next step (1).",
    "Defines the INFORM language level (0: Basic, 1: Standard, 2: Extended).",
    "Enables (1) or disables (0) retention of instruction values in the message line.",
    "Sets the Step/Test procedure mode to EASY (0) or ALL (1).",
    "Write protection of tool number for post-teach.",
    "Allows (0) or prevents (1) post-teach of only the moved axis group.",
    "Enables (1) or disables (0) the tool number switching function (TOOL NO. SWITCHING).",
    "Parameter required to enable the use of the SETUALM command (User Alarm).",
    "Enables (1) or disables (0) the recycle bin for restoring deleted JOBs.",
    "Allows (0) or prevents (1) the use of 64 tool files (TCP).",
    "Tool calibration method: coordinates only (0), position only (1), coordinates and position (2).",
    "Enables (0) or disables (1) the audible beep during position teaching.",
    "Enables (1) or disables (0) the display of dual coordinates with SHIFT function.",
    "Allows or prevents backward step (BWD) without axis group or in parallel jobs.",
    "Function for improving alarm display processing.",
    "Software limits for Robot 2 on the positive and negative sides of X, Y and Z axes.",
    "Specifies whether input group data (1-256) is handled as binary or BCD.",
    "Specifies whether output group data (1-256) is handled as binary or BCD.",
    "Data management (binary/BCD) for input groups 257 to 512.",
    "Data management (binary/BCD) for output groups 257 to 512.",
    "Parameter related to the Tool File in functional safety (FSU).",
    "Tool interference protection file (FSU).",
    "Home position calibration data (FSU).",
    "Axis motion range limit data (FSU).",
    "Axis speed monitoring data (FSU).",
    "Robot motion range limit data (FSU).",
    "Speed limit data (FSU).",
    "Tool angle monitoring data (FSU).",
    "Tool change monitoring / Tool number selection (FSU).",
    "Functional definition, system, SERVO and servo motor parameters (FSU).",
    "Robot match parameter for the SETTOOL instruction.",
    "Specifies the application (e.g. 0 for arc welding).",
    "Welding start condition file assignment for power source 2.",
]

_PARAMS_DESC_FR = [
    "Limite la création du fichier de sauvegarde automatique à une seule fois par jour (0 : Désactivé, 1 : Activé).",
    "Limite supérieure de vitesse pour l'opération IN-GUARD-SAFE (unité : 0,01 %).",
    "Vitesse de liaison pour l'opération Jog au niveau LOW.",
    "Vitesse de liaison pour l'opération Jog au niveau MEDIUM.",
    "Vitesse de liaison pour l'opération Jog au niveau HIGH.",
    "Vitesse de liaison pour l'opération Jog au niveau HIGH SPEED.",
    "Vitesse de retour à la position WORK HOME par rapport à la vitesse maximale (unité : 0,01 %).",
    "Vitesse maximale pour les fonctions de recherche (Search) (unité : 0,1 mm/s).",
    "Limitation de vitesse manuelle pour le fonctionnement pas à pas (unité : 0,01 %).",
    "Limitation de vitesse manuelle pour le fonctionnement Basse vitesse (unité : 0,01 %).",
    "Limitation de vitesse manuelle pour le fonctionnement Vitesse moyenne (unité : 0,01 %).",
    "Spécifie (en bits) l'axe pour la sortie de position actuelle (commande) dans les registres.",
    "Spécifie (en bits) l'axe pour la sortie de position actuelle (retour) dans les registres.",
    "Définit si les coordonnées du robot sont rectangulaires (0) ou cylindriques (1).",
    "Contrôle de la posture lors de l'opération de Jog cartésien.",
    "Permet (0) ou bloque (1) la modification des étapes uniquement dans le programme.",
    "Insertion de l'instruction MOVE : sous la ligne (0) ou après l'étape suivante (1).",
    "Définit le niveau du langage INFORM (0 : Base, 1 : Standard, 2 : Étendu).",
    "Active (1) ou désactive (0) le maintien des valeurs d'instruction dans la ligne de message.",
    "Définit le mode Pas/Procédure de test sur FACILE (0) ou TOUT (1).",
    "Protection en écriture du numéro d'outil pour le post-teach.",
    "Permet (0) ou bloque (1) le post-teach du seul groupe d'axes déplacé.",
    "Active (1) ou désactive (0) la fonction de commutation du numéro d'outil (TOOL NO. SWITCHING).",
    "Paramètre nécessaire pour activer l'utilisation de la commande SETUALM (Alarme utilisateur).",
    "Active (1) ou désactive (0) la corbeille pour la restauration des JOBs supprimés.",
    "Permet (0) ou bloque (1) l'utilisation de 64 fichiers outil (TCP).",
    "Méthode d'étalonnage de l'outil : coordonnées uniquement (0), position uniquement (1), coordonnées et position (2).",
    "Active (0) ou désactive (1) le signal sonore (bip) lors de l'apprentissage des positions.",
    "Active (1) ou désactive (0) l'affichage des coordonnées doubles avec la fonction SHIFT.",
    "Permet ou bloque le pas en arrière (BWD) sans groupe d'axes ou dans des jobs parallèles.",
    "Fonction d'amélioration du traitement de l'affichage des alarmes.",
    "Limites logicielles pour le Robot 2 sur les côtés positif et négatif des axes X, Y et Z.",
    "Spécifie si les données des groupes d'entrée (1-256) sont gérées en binaire ou en BCD.",
    "Spécifie si les données des groupes de sortie (1-256) sont gérées en binaire ou en BCD.",
    "Gestion des données (binaire/BCD) pour les groupes d'entrée de 257 à 512.",
    "Gestion des données (binaire/BCD) pour les groupes de sortie de 257 à 512.",
    "Paramètre relatif au fichier outil (Tool File) dans la sécurité fonctionnelle (FSU).",
    "Fichier de protection contre les interférences de l'outil (FSU).",
    "Données d'étalonnage de la position Home (FSU).",
    "Données de limite du rayon d'action des axes (FSU).",
    "Données de surveillance de la vitesse des axes (FSU).",
    "Données de limite du rayon d'action du robot (FSU).",
    "Données de limite de vitesse (FSU).",
    "Données de surveillance de l'angle de l'outil (FSU).",
    "Surveillance du changement d'outil / Sélection du numéro d'outil (FSU).",
    "Paramètres de définition fonctionnelle, système, SERVO et servomoteur (FSU).",
    "Paramètre de correspondance robot (Robot match parameter) pour l'instruction SETTOOL.",
    "Spécifie l'application (ex. 0 pour la soudure à l'arc).",
    "Attribution du fichier de conditions de début de soudure pour la source d'alimentation 2.",
]

_PARAMS_DESC_ES = [
    "Limita la creación del archivo de copia de seguridad automática a una vez al día (0: Desactivado, 1: Activado).",
    "Límite superior de velocidad para la operación IN-GUARD-SAFE (unidad: 0,01%).",
    "Velocidad de enlace para la operación Jog en nivel LOW.",
    "Velocidad de enlace para la operación Jog en nivel MEDIUM.",
    "Velocidad de enlace para la operación Jog en nivel HIGH.",
    "Velocidad de enlace para la operación Jog en nivel HIGH SPEED.",
    "Velocidad de retorno a la posición WORK HOME respecto a la velocidad máxima (unidad: 0,01%).",
    "Velocidad máxima para las funciones de búsqueda (Search) (unidad: 0,1 mm/s).",
    "Limitación de velocidad manual para funcionamiento paso a paso (unidad: 0,01%).",
    "Limitación de velocidad manual para funcionamiento Baja velocidad (unidad: 0,01%).",
    "Limitación de velocidad manual para funcionamiento Velocidad media (unidad: 0,01%).",
    "Especifica (en bits) el eje para la salida de posición actual (comando) en los registros.",
    "Especifica (en bits) el eje para la salida de posición actual (retroalimentación) en los registros.",
    "Define si las coordenadas del robot son rectangulares (0) o cilíndricas (1).",
    "Control de postura durante la operación de Jog cartesiano.",
    "Permite (0) o bloquea (1) solo la modificación de pasos en el programa.",
    "Inserción de instrucción MOVE: debajo de la línea (0) o después del siguiente paso (1).",
    "Define el nivel del lenguaje INFORM (0: Básico, 1: Estándar, 2: Extendido).",
    "Habilita (1) o deshabilita (0) el mantenimiento de valores de instrucción en la línea de mensaje.",
    "Establece el modo Paso/Procedimiento de prueba en FÁCIL (0) o TODO (1).",
    "Protección de escritura del número de herramienta para el post-teach.",
    "Permite (0) o bloquea (1) el post-teach solo del grupo de ejes desplazado.",
    "Habilita (1) o deshabilita (0) la función de conmutación del número de herramienta (TOOL NO. SWITCHING).",
    "Parámetro necesario para habilitar el uso del comando SETUALM (Alarma de usuario).",
    "Activa (1) o desactiva (0) la papelera para restaurar los JOBs eliminados.",
    "Permite (0) o bloquea (1) el uso de 64 archivos de herramienta (TCP).",
    "Método de calibración de herramienta: solo coordenadas (0), solo posición (1), coordenadas y posición (2).",
    "Activa (0) o desactiva (1) la señal acústica (bip) durante el teach de posiciones.",
    "Habilita (1) o deshabilita (0) la visualización de coordenadas dobles con función SHIFT.",
    "Permite o bloquea el paso hacia atrás (BWD) sin grupo de ejes o en jobs paralelos.",
    "Función de mejora del procesamiento de visualización de alarmas.",
    "Límites de software para Robot 2 en los lados positivo y negativo de los ejes X, Y y Z.",
    "Especifica si los datos de los grupos de entrada (1-256) se gestionan como binario o BCD.",
    "Especifica si los datos de los grupos de salida (1-256) se gestionan como binario o BCD.",
    "Gestión de datos (binario/BCD) para grupos de entrada de 257 a 512.",
    "Gestión de datos (binario/BCD) para grupos de salida de 257 a 512.",
    "Parámetro relacionado con el archivo de herramienta (Tool File) en la seguridad funcional (FSU).",
    "Archivo de protección contra interferencias de herramienta (FSU).",
    "Datos de calibración de posición Home (FSU).",
    "Datos de límite del radio de acción de los ejes (FSU).",
    "Datos de monitoreo de velocidad de los ejes (FSU).",
    "Datos de límite del radio de acción del robot (FSU).",
    "Datos de límite de velocidad (FSU).",
    "Datos de monitoreo del ángulo de herramienta (FSU).",
    "Monitoreo de cambio de herramienta / Selección del número de herramienta (FSU).",
    "Parámetros de definición funcional, sistema, SERVO y servomotor (FSU).",
    "Parámetro de correspondencia de robot (Robot match parameter) para la instrucción SETTOOL.",
    "Especifica la aplicación (p.ej. 0 para soldadura por arco).",
    "Asignación del archivo de condiciones de inicio de soldadura para la fuente de alimentación 2.",
]

_PARAMS_DESC_UA = [
    "Обмежує автоматичне створення файлу резервної копії до одного разу на день (0: Вимкнено, 1: Увімкнено).",
    "Верхній ліміт швидкості для операції IN-GUARD-SAFE (одиниця: 0,01%).",
    "Швидкість з'єднання для операції Jog на рівні LOW.",
    "Швидкість з'єднання для операції Jog на рівні MEDIUM.",
    "Швидкість з'єднання для операції Jog на рівні HIGH.",
    "Швидкість з'єднання для операції Jog на рівні HIGH SPEED.",
    "Швидкість повернення до позиції WORK HOME відносно максимальної швидкості (одиниця: 0,01%).",
    "Максимальна швидкість для функцій пошуку (Search) (одиниця: 0,1 мм/с).",
    "Обмеження ручної швидкості для покрокового режиму (одиниця: 0,01%).",
    "Обмеження ручної швидкості для режиму Низька швидкість (одиниця: 0,01%).",
    "Обмеження ручної швидкості для режиму Середня швидкість (одиниця: 0,01%).",
    "Задає (у бітах) вісь для виводу поточної позиції (команда) у регістрах.",
    "Задає (у бітах) вісь для виводу поточної позиції (зворотній зв'язок) у регістрах.",
    "Визначає, чи є координати робота прямокутними (0) чи циліндричними (1).",
    "Контроль пози під час декартової операції Jog.",
    "Дозволяє (0) або блокує (1) лише зміну кроків у програмі.",
    "Вставка інструкції MOVE: нижче рядка (0) або після наступного кроку (1).",
    "Визначає рівень мови INFORM (0: Базовий, 1: Стандартний, 2: Розширений).",
    "Вмикає (1) або вимикає (0) збереження значень інструкцій у рядку повідомлення.",
    "Встановлює режим Крок/Тестова процедура на ЛЕГКО (0) або ВСЕ (1).",
    "Захист від запису номера інструменту для post-teach.",
    "Дозволяє (0) або блокує (1) post-teach лише переміщеної групи осей.",
    "Вмикає (1) або вимикає (0) функцію перемикання номера інструменту (TOOL NO. SWITCHING).",
    "Параметр, необхідний для увімкнення команди SETUALM (Аварія користувача).",
    "Вмикає (1) або вимикає (0) кошик для відновлення видалених JOBів.",
    "Дозволяє (0) або блокує (1) використання 64 файлів інструментів (TCP).",
    "Метод калібрування інструменту: лише координати (0), лише позиція (1), координати та позиція (2).",
    "Вмикає (0) або вимикає (1) звуковий сигнал під час навчання позицій.",
    "Вмикає (1) або вимикає (0) відображення подвійних координат із функцією SHIFT.",
    "Дозволяє або блокує крок назад (BWD) без групи осей або у паралельних завданнях.",
    "Функція покращення обробки відображення аварій.",
    "Програмні межі для Робота 2 з позитивного та негативного боків осей X, Y та Z.",
    "Визначає, чи обробляються дані груп вхідних сигналів (1-256) як двійкові або BCD.",
    "Визначає, чи обробляються дані груп вихідних сигналів (1-256) як двійкові або BCD.",
    "Управління даними (двійкові/BCD) для груп вхідних сигналів від 257 до 512.",
    "Управління даними (двійкові/BCD) для груп вихідних сигналів від 257 до 512.",
    "Параметр, пов'язаний із файлом інструменту (Tool File) у функціональній безпеці (FSU).",
    "Файл захисту від інтерференції інструменту (FSU).",
    "Дані калібрування позиції Home (FSU).",
    "Дані обмеження діапазону руху осей (FSU).",
    "Дані моніторингу швидкості осей (FSU).",
    "Дані обмеження діапазону руху робота (FSU).",
    "Дані обмеження швидкості (FSU).",
    "Дані моніторингу кута інструменту (FSU).",
    "Моніторинг зміни інструменту / Вибір номера інструменту (FSU).",
    "Параметри функціонального визначення, системи, SERVO та серводвигуна (FSU).",
    "Параметр відповідності робота (Robot match parameter) для інструкції SETTOOL.",
    "Задає застосування (напр. 0 для дугового зварювання).",
    "Призначення файлу умов початку зварювання для джерела живлення 2.",
]

_PARAMS_DESC_JA = [
    "自動バックアップファイルの作成を1日1回に制限します（0：無効、1：有効）。",
    "IN-GUARD-SAFE動作の速度上限（単位：0.01%）。",
    "LOWレベルでのJog動作リンク速度。",
    "MEDIUMレベルでのJog動作リンク速度。",
    "HIGHレベルでのJog動作リンク速度。",
    "HIGH SPEEDレベルでのJog動作リンク速度。",
    "最高速度に対するWORK HOME位置への復帰速度（単位：0.01%）。",
    "サーチ機能の最大速度（単位：0.1 mm/s）。",
    "ステップ動作時の手動速度制限（単位：0.01%）。",
    "低速動作時の手動速度制限（単位：0.01%）。",
    "中速動作時の手動速度制限（単位：0.01%）。",
    "レジスタへの現在位置（指令）出力軸をビットで指定。",
    "レジスタへの現在位置（フィードバック）出力軸をビットで指定。",
    "ロボット座標系が直交（0）か円筒（1）かを定義。",
    "デカルトJog動作時の姿勢制御。",
    "プログラム内のステップのみの変更を許可（0）または禁止（1）。",
    "MOVE命令挿入位置：行の下（0）または次のステップの後（1）。",
    "INFORMの言語レベルを定義（0：基本、1：標準、2：拡張）。",
    "メッセージ行の命令値保持を有効（1）または無効（0）。",
    "テストステップ/手順モードをEASY（0）またはALL（1）に設定。",
    "ポストティーチ時のツール番号への書き込み保護。",
    "移動した軸グループのみのポストティーチを許可（0）または禁止（1）。",
    "ツール番号切り替え機能（TOOL NO. SWITCHING）を有効（1）または無効（0）。",
    "SETUALMコマンド（ユーザーアラーム）使用に必要なパラメータ。",
    "削除されたJOBを復元するためのゴミ箱を有効（1）または無効（0）。",
    "64ツールファイル（TCP）の使用を許可（0）または禁止（1）。",
    "ツールキャリブレーション方法：座標のみ（0）、位置のみ（1）、座標と位置（2）。",
    "位置ティーチ中の音響ビープを有効（0）または無効（1）。",
    "SHIFT機能による二重座標表示を有効（1）または無効（0）。",
    "軸グループなしまたは並列ジョブでの後退ステップ（BWD）を許可または禁止。",
    "アラーム表示処理改善機能。",
    "ロボット2のX、Y、Z軸の正負方向のソフトウェア制限。",
    "入力グループデータ（1-256）をバイナリまたはBCDで管理するかを指定。",
    "出力グループデータ（1-256）をバイナリまたはBCDで管理するかを指定。",
    "入力グループ257～512のデータ管理（バイナリ/BCD）。",
    "出力グループ257～512のデータ管理（バイナリ/BCD）。",
    "機能安全（FSU）のツールファイルに関するパラメータ。",
    "ツール干渉保護ファイル（FSU）。",
    "ホーム位置キャリブレーションデータ（FSU）。",
    "軸動作範囲制限データ（FSU）。",
    "軸速度監視データ（FSU）。",
    "ロボット動作範囲制限データ（FSU）。",
    "速度制限データ（FSU）。",
    "ツール角度監視データ（FSU）。",
    "ツール交換監視 / ツール番号選択（FSU）。",
    "機能定義、システム、SERVOおよびサーボモータパラメータ（FSU）。",
    "SETTOOL命令のロボット対応パラメータ（Robot match parameter）。",
    "アプリケーションを指定（例：0はアーク溶接）。",
    "電源2の溶接開始条件ファイル割り当て。",
]

_PARAMS_DESC = {
    "IT": _PARAMS_DESC_IT,
    "EN": _PARAMS_DESC_EN,
    "FR": _PARAMS_DESC_FR,
    "ES": _PARAMS_DESC_ES,
    "UA": _PARAMS_DESC_UA,
    "JA": _PARAMS_DESC_JA,
}


def get_params(lang="IT"):
    """Return list of (code, description) for the requested language."""
    descs = _PARAMS_DESC.get(lang, _PARAMS_DESC_IT)
    return list(zip(_PARAMS_CODES, descs))


# ═══════════════════════════════════════════════════════════════════════════════
# KNOWN_PARAMS_DATA  (source: YASKAWA2.md, deduplicated)
# 3 columns: code, value, description
# ═══════════════════════════════════════════════════════════════════════════════

_KNOWN_CODES = [
    "S2C0230", "S2C0231", "S2C0232", "S2C0235",
    "S2C0264", "S2C0265", "S2C0266",
    "S2C0421", "S2C0422",
    "S2C 395", "S2C 396",
    "S2C0430", "S2C0437", "S2C0438", "S2C0450", "S2C0699",
    "S2C0700", "S2C0701", "S2C0702",
    "S2C0709", "S2C1291", "S2C1364", "S2C1590", "S2C1699", "S2C1809",
    "S3C1192", "S3C1193",
    "S4C0083", "S4C0084", "S4C0085", "S4C0086", "S4C0087",
    "S4C0287", "S4C0288", "S4C0295",
    "RS59", "RS89", "RS214", "#87015",
    "R01Gx013", "R01Gx014", "S1C1G33",
]

_KNOWN_VALUES = [
    "63", "1", "1", "0",
    "1", "1", "1",
    "1", "1",
    "0", "0",
    "2", "1", "1", "1", "13",
    "2", "1", "1",
    "1", "1", "1", "7", "1", "1",
    "999999999", "999999999",
    "65535", "65535", "65535", "65535", "65535",
    "50", "0", "0",
    "3", "1", "1", "ON",
    "-300000", "-300000", "12500",
]

_KNOWN_DESC_IT = [
    "Abilita determinate possibilità (tra cui lo start del programma da PP) anche se il PP è in remoto",
    "Abilita la possibilità di comandare il PSTART anche in TEST START",
    "Abilita la possibilità di comandare il PSTART anche in TEST START",
    "Mantiene i valori dei GPO al riavvio",
    "Permette di leggere il valore in mm degli assi esterni; senza di questo il valore si può leggere solo in PULSE",
    "Permette di leggere il valore in mm degli assi esterni; senza di questo il valore si può leggere solo in PULSE",
    "Permette di leggere il valore in mm degli assi esterni; senza di questo il valore si può leggere solo in PULSE",
    "Abilita System JOB",
    "Abilita System JOB",
    "Permette di caricare IONAME.DAT con i nomi che vuoi (DISABILITA ALIAS FUNCTION X IONAME.DAT)",
    "Permette di caricare VARNAME.DAT con i nomi che vuoi (DISABILITA ALIAS FUNCTION X VARNAME.DAT)",
    "Smoothing movimenti (in teoria per evitare allarme di EXCESSIVE SPEED)",
    "Ricorda il punto del cursore sul PP ed esegue la domanda nel caso in cui venga spostato",
    "Permette di vedere la chiamata di una macro come una CALL, quindi ci entra dentro",
    "Abilita la possibilità di modificare il tool in maniera dinamica anche con FSU attivo (BISOGNA ESSERE IN YASKAWA MODE)",
    "Mette la velocità a LOW ogni volta che si passa da PLAY a TEACH, ogni volta che si esegue un SERVO ON e ogni volta che vengono modificate le coordinate di esercizio",
    "Permette la modifica delle coordinate cartesiane dei frame",
    "Permettono la modifica dinamica dell'override",
    "Per impostazione override da IF/Panel",
    "",
    "Servono per evitare che il robot si fermi quando incontra un Wait già verificato",
    "Abilita l'autostart del Remote Pendant Server all'avvio del robot",
    "",
    "Abilita la gestione dello STOP MODE nel SETUALM anche dentro al System Job",
    "",
    "Aumenta il limite massimo di spostamento del tool attraverso la funzione SET TOOL",
    "Aumenta il limite massimo di spostamento del tool attraverso la funzione SET TOOL",
    "Rende ritentivi tutti gli Auxiliary Relay dal #71930 al #72567",
    "Rende ritentivi tutti gli Auxiliary Relay dal #72570 al #73207",
    "Rende ritentivi tutti gli Auxiliary Relay dal #73210 al #73847",
    "Rende ritentivi tutti gli Auxiliary Relay dal #73850 al #74487",
    "Rende ritentivi tutti gli Auxiliary Relay dal #74490 al #75127",
    "Byte di GPI da utilizzare per il cambio override dinamico",
    "Lascio tutti questi parametri a 0 in modo che venga preso come valore % di override il numero nel byte del parametro S4C0287",
    "",
    "Possibilità di sovrascrivere i Job caricati dalla USB senza doverli cancellare",
    "1 = Scambio comunicazione FTP",
    "Possibilità di sovrascrivere i Job da FTP",
    "Permette di fare in Remote le stesse cose che faccio in Play",
    "Inclinazioni su asse X — dipende dalla macchina (ORION OMC)",
    "Inclinazioni su asse Y — inclinazione robot (modificabile solo da Yaskawa)",
    "Micro di raccordo nelle movimentazioni in PL=1",
]

_KNOWN_DESC_EN = [
    "Enables certain functions (including program start from PP) even when PP is in remote mode",
    "Enables the ability to command PSTART also in TEST START mode",
    "Enables the ability to command PSTART also in TEST START mode",
    "Retains GPO values on restart",
    "Allows reading external axis values in mm; without this, values can only be read in PULSE",
    "Allows reading external axis values in mm; without this, values can only be read in PULSE",
    "Allows reading external axis values in mm; without this, values can only be read in PULSE",
    "Enables System JOB",
    "Enables System JOB",
    "Allows loading IONAME.DAT with custom names (DISABLES ALIAS FUNCTION FOR IONAME.DAT)",
    "Allows loading VARNAME.DAT with custom names (DISABLES ALIAS FUNCTION FOR VARNAME.DAT)",
    "Motion smoothing (theoretically to avoid EXCESSIVE SPEED alarm)",
    "Remembers the cursor position on the PP and prompts if it is moved",
    "Allows viewing a macro call as a CALL, so the debugger steps into it",
    "Enables dynamic tool modification even with FSU active (MUST BE IN YASKAWA MODE)",
    "Sets speed to LOW every time switching from PLAY to TEACH, every SERVO ON, and every time exercise coordinates are modified",
    "Allows modification of Cartesian frame coordinates",
    "Allows dynamic override modification",
    "For override setting from IF/Panel",
    "",
    "Used to prevent the robot from stopping when it encounters an already-satisfied Wait",
    "Enables autostart of the Remote Pendant Server on robot startup",
    "",
    "Enables STOP MODE management in SETUALM also inside the System Job",
    "",
    "Increases the maximum tool displacement limit via the SET TOOL function",
    "Increases the maximum tool displacement limit via the SET TOOL function",
    "Makes all Auxiliary Relays from #71930 to #72567 retentive",
    "Makes all Auxiliary Relays from #72570 to #73207 retentive",
    "Makes all Auxiliary Relays from #73210 to #73847 retentive",
    "Makes all Auxiliary Relays from #73850 to #74487 retentive",
    "Makes all Auxiliary Relays from #74490 to #75127 retentive",
    "GPI byte to use for dynamic override change",
    "Set all these parameters to 0 so that the override % value is taken from the byte in parameter S4C0287",
    "",
    "Ability to overwrite Jobs loaded from USB without having to delete them first",
    "1 = FTP communication exchange",
    "Ability to overwrite Jobs via FTP",
    "Allows doing in Remote the same things as in Play mode",
    "X-axis inclination — machine-dependent (ORION OMC)",
    "Y-axis inclination — robot tilt (modifiable only by Yaskawa)",
    "Micro-blend for movements at PL=1",
]

_KNOWN_DESC_FR = [
    "Active certaines possibilités (dont le démarrage du programme depuis PP) même si PP est en mode distant",
    "Active la possibilité de commander le PSTART même en TEST START",
    "Active la possibilité de commander le PSTART même en TEST START",
    "Conserve les valeurs des GPO au redémarrage",
    "Permet de lire la valeur en mm des axes externes ; sans cela, la valeur ne peut être lue qu'en PULSE",
    "Permet de lire la valeur en mm des axes externes ; sans cela, la valeur ne peut être lue qu'en PULSE",
    "Permet de lire la valeur en mm des axes externes ; sans cela, la valeur ne peut être lue qu'en PULSE",
    "Active le System JOB",
    "Active le System JOB",
    "Permet de charger IONAME.DAT avec les noms souhaités (DÉSACTIVE LA FONCTION ALIAS POUR IONAME.DAT)",
    "Permet de charger VARNAME.DAT avec les noms souhaités (DÉSACTIVE LA FONCTION ALIAS POUR VARNAME.DAT)",
    "Lissage des mouvements (en théorie pour éviter l'alarme EXCESSIVE SPEED)",
    "Mémorise la position du curseur sur le PP et pose la question si elle est déplacée",
    "Permet de voir l'appel d'une macro comme un CALL, permettant d'y entrer",
    "Active la possibilité de modifier l'outil dynamiquement même avec FSU actif (DOIT ÊTRE EN MODE YASKAWA)",
    "Met la vitesse à LOW à chaque passage de PLAY à TEACH, à chaque SERVO ON et à chaque modification des coordonnées d'exercice",
    "Permet la modification des coordonnées cartésiennes des frames",
    "Permet la modification dynamique de l'override",
    "Pour le réglage de l'override depuis IF/Panel",
    "",
    "Sert à éviter que le robot s'arrête lorsqu'il rencontre un Wait déjà vérifié",
    "Active le démarrage automatique du Remote Pendant Server au démarrage du robot",
    "",
    "Active la gestion du STOP MODE dans SETUALM aussi à l'intérieur du System Job",
    "",
    "Augmente la limite maximale de déplacement de l'outil via la fonction SET TOOL",
    "Augmente la limite maximale de déplacement de l'outil via la fonction SET TOOL",
    "Rend rétentifs tous les Auxiliary Relay de #71930 à #72567",
    "Rend rétentifs tous les Auxiliary Relay de #72570 à #73207",
    "Rend rétentifs tous les Auxiliary Relay de #73210 à #73847",
    "Rend rétentifs tous les Auxiliary Relay de #73850 à #74487",
    "Rend rétentifs tous les Auxiliary Relay de #74490 à #75127",
    "Octet GPI à utiliser pour le changement d'override dynamique",
    "Laisser tous ces paramètres à 0 pour que la valeur % d'override soit prise dans l'octet du paramètre S4C0287",
    "",
    "Possibilité d'écraser les Jobs chargés depuis USB sans avoir à les supprimer",
    "1 = Échange de communication FTP",
    "Possibilité d'écraser les Jobs depuis FTP",
    "Permet de faire en Remote les mêmes choses qu'en Play",
    "Inclinaison sur l'axe X — dépend de la machine (ORION OMC)",
    "Inclinaison sur l'axe Y — inclinaison du robot (modifiable uniquement par Yaskawa)",
    "Micro-raccordement dans les mouvements en PL=1",
]

_KNOWN_DESC_ES = [
    "Habilita ciertas posibilidades (incluido el inicio del programa desde PP) incluso si PP está en remoto",
    "Habilita la posibilidad de comandar PSTART también en TEST START",
    "Habilita la posibilidad de comandar PSTART también en TEST START",
    "Mantiene los valores de GPO al reiniciar",
    "Permite leer el valor en mm de los ejes externos; sin esto, el valor solo puede leerse en PULSE",
    "Permite leer el valor en mm de los ejes externos; sin esto, el valor solo puede leerse en PULSE",
    "Permite leer el valor en mm de los ejes externos; sin esto, el valor solo puede leerse en PULSE",
    "Habilita System JOB",
    "Habilita System JOB",
    "Permite cargar IONAME.DAT con los nombres deseados (DESHABILITA LA FUNCIÓN ALIAS PARA IONAME.DAT)",
    "Permite cargar VARNAME.DAT con los nombres deseados (DESHABILITA LA FUNCIÓN ALIAS PARA VARNAME.DAT)",
    "Suavizado de movimientos (en teoría para evitar la alarma de EXCESSIVE SPEED)",
    "Recuerda el punto del cursor en el PP y hace la pregunta si se mueve",
    "Permite ver la llamada de una macro como una CALL, entrando dentro de ella",
    "Habilita la modificación dinámica del tool incluso con FSU activo (DEBE ESTAR EN MODO YASKAWA)",
    "Pone la velocidad en LOW cada vez que se cambia de PLAY a TEACH, en cada SERVO ON y cuando se modifican las coordenadas de ejercicio",
    "Permite la modificación de las coordenadas cartesianas de los frames",
    "Permite la modificación dinámica del override",
    "Para ajuste de override desde IF/Panel",
    "",
    "Sirve para evitar que el robot se detenga cuando encuentra un Wait ya verificado",
    "Habilita el autostart del Remote Pendant Server al inicio del robot",
    "",
    "Habilita la gestión del STOP MODE en SETUALM también dentro del System Job",
    "",
    "Aumenta el límite máximo de desplazamiento del tool a través de la función SET TOOL",
    "Aumenta el límite máximo de desplazamiento del tool a través de la función SET TOOL",
    "Hace retentivos todos los Auxiliary Relay del #71930 al #72567",
    "Hace retentivos todos los Auxiliary Relay del #72570 al #73207",
    "Hace retentivos todos los Auxiliary Relay del #73210 al #73847",
    "Hace retentivos todos los Auxiliary Relay del #73850 al #74487",
    "Hace retentivos todos los Auxiliary Relay del #74490 al #75127",
    "Byte de GPI a utilizar para el cambio de override dinámico",
    "Dejar todos estos parámetros en 0 para que el valor % de override sea el número en el byte del parámetro S4C0287",
    "",
    "Posibilidad de sobrescribir los Jobs cargados desde USB sin necesidad de borrarlos",
    "1 = Intercambio de comunicación FTP",
    "Posibilidad de sobrescribir Jobs desde FTP",
    "Permite hacer en Remote las mismas cosas que en Play",
    "Inclinación en eje X — depende de la máquina (ORION OMC)",
    "Inclinación en eje Y — inclinación del robot (modificable solo por Yaskawa)",
    "Micro de enlace en movimientos en PL=1",
]

_KNOWN_DESC_UA = [
    "Вмикає певні можливості (включаючи запуск програми з PP) навіть якщо PP у дистанційному режимі",
    "Вмикає можливість керування PSTART також у режимі TEST START",
    "Вмикає можливість керування PSTART також у режимі TEST START",
    "Зберігає значення GPO при перезапуску",
    "Дозволяє зчитувати значення зовнішніх осей у мм; без цього значення можна зчитати лише в PULSE",
    "Дозволяє зчитувати значення зовнішніх осей у мм; без цього значення можна зчитати лише в PULSE",
    "Дозволяє зчитувати значення зовнішніх осей у мм; без цього значення можна зчитати лише в PULSE",
    "Вмикає System JOB",
    "Вмикає System JOB",
    "Дозволяє завантажувати IONAME.DAT з потрібними іменами (ВИМИКАЄ ФУНКЦІЮ ALIAS ДЛЯ IONAME.DAT)",
    "Дозволяє завантажувати VARNAME.DAT з потрібними іменами (ВИМИКАЄ ФУНКЦІЮ ALIAS ДЛЯ VARNAME.DAT)",
    "Згладжування рухів (теоретично для уникнення аварії EXCESSIVE SPEED)",
    "Запам'ятовує положення курсора на PP та запитує, якщо воно змінено",
    "Дозволяє бачити виклик макросу як CALL, тому можна зайти всередину",
    "Вмикає можливість динамічної зміни інструменту навіть з активним FSU (НЕОБХІДНО БУТИ В РЕЖИМІ YASKAWA)",
    "Встановлює швидкість на LOW при кожному переході з PLAY на TEACH, при кожному SERVO ON та при кожній зміні координат вправи",
    "Дозволяє змінювати декартові координати кадрів",
    "Дозволяє динамічну зміну перевизначення (override)",
    "Для налаштування перевизначення з IF/Panel",
    "",
    "Використовується для запобігання зупинки робота при зустрічі вже виконаного Wait",
    "Вмикає автозапуск Remote Pendant Server при запуску робота",
    "",
    "Вмикає управління STOP MODE у SETUALM також всередині System Job",
    "",
    "Збільшує максимальне обмеження переміщення інструменту через функцію SET TOOL",
    "Збільшує максимальне обмеження переміщення інструменту через функцію SET TOOL",
    "Робить усі Auxiliary Relay від #71930 до #72567 утримуючими",
    "Робить усі Auxiliary Relay від #72570 до #73207 утримуючими",
    "Робить усі Auxiliary Relay від #73210 до #73847 утримуючими",
    "Робить усі Auxiliary Relay від #73850 до #74487 утримуючими",
    "Робить усі Auxiliary Relay від #74490 до #75127 утримуючими",
    "Байт GPI для динамічної зміни перевизначення",
    "Залишити всі ці параметри рівними 0, щоб значення % перевизначення бралося з байта параметра S4C0287",
    "",
    "Можливість перезаписувати завдання, завантажені з USB, без необхідності їх видалення",
    "1 = Обмін зв'язком FTP",
    "Можливість перезаписувати завдання через FTP",
    "Дозволяє в Remote виконувати ті ж дії, що і в Play",
    "Нахил по осі X — залежить від машини (ORION OMC)",
    "Нахил по осі Y — нахил робота (змінюється лише Yaskawa)",
    "Мікро-сполучення для переміщень при PL=1",
]

_KNOWN_DESC_JA = [
    "PPがリモートモードの場合でも、特定の機能（PPからのプログラム起動など）を有効化",
    "TEST STARTモードでもPSTARTのコマンドを可能にする",
    "TEST STARTモードでもPSTARTのコマンドを可能にする",
    "再起動時にGPO値を保持",
    "外部軸の値をmmで読み取ることを許可；なければPULSEでのみ読み取り可能",
    "外部軸の値をmmで読み取ることを許可；なければPULSEでのみ読み取り可能",
    "外部軸の値をmmで読み取ることを許可；なければPULSEでのみ読み取り可能",
    "System JOBを有効化",
    "System JOBを有効化",
    "IONAME.DATを任意の名称でロード可能（IONAME.DATのエイリアス機能を無効化）",
    "VARNAME.DATを任意の名称でロード可能（VARNAME.DATのエイリアス機能を無効化）",
    "動作スムージング（理論上はEXCESSIVE SPEEDアラームを防ぐため）",
    "PP上のカーソル位置を記憶し、移動した場合に確認を促す",
    "マクロ呼び出しをCALLとして表示し、内部にステップインできるようにする",
    "FSUが有効な場合でも動的ツール変更を可能にする（YASKAWAモードが必要）",
    "PLAYからTEACHへの切り替え、SERVO ON、運動座標変更時に速度をLOWに設定",
    "フレームのデカルト座標の変更を許可",
    "オーバーライドの動的変更を許可",
    "IF/Panelからのオーバーライド設定用",
    "",
    "既に成立したWaitに遭遇してもロボットが停止しないようにする",
    "ロボット起動時にRemote Pendant Serverを自動起動",
    "",
    "System Job内でもSETUALMのSTOP MODEを管理可能にする",
    "",
    "SET TOOL機能によるツール最大移動制限を増加",
    "SET TOOL機能によるツール最大移動制限を増加",
    "#71930〜#72567の全Auxiliary Relayを保持型にする",
    "#72570〜#73207の全Auxiliary Relayを保持型にする",
    "#73210〜#73847の全Auxiliary Relayを保持型にする",
    "#73850〜#74487の全Auxiliary Relayを保持型にする",
    "#74490〜#75127の全Auxiliary Relayを保持型にする",
    "動的オーバーライド変更に使用するGPIバイト",
    "これらのパラメータを全て0にすることで、オーバーライド%はS4C0287のバイト値から取得",
    "",
    "削除せずにUSBからロードしたジョブを上書き可能",
    "1 = FTP通信交換",
    "FTP経由でジョブを上書き可能",
    "Remoteモードでもplayモードと同じ操作を許可",
    "X軸の傾き — 機械依存（ORION OMC）",
    "Y軸の傾き — ロボット傾斜（Yaskawaのみ変更可）",
    "PL=1での動作時のマイクロブレンド",
]

_KNOWN_DESC = {
    "IT": _KNOWN_DESC_IT,
    "EN": _KNOWN_DESC_EN,
    "FR": _KNOWN_DESC_FR,
    "ES": _KNOWN_DESC_ES,
    "UA": _KNOWN_DESC_UA,
    "JA": _KNOWN_DESC_JA,
}


def get_known_params(lang="IT"):
    """Return list of (code, value, description) for the requested language."""
    descs = _KNOWN_DESC.get(lang, _KNOWN_DESC_IT)
    return list(zip(_KNOWN_CODES, _KNOWN_VALUES, descs))
